In [28]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)
sns.set(style="whitegrid")

In [29]:
#Loading my data
races = pd.read_csv("../data/races.csv")
results = pd.read_csv("../data/results.csv")
constructors = pd.read_csv("../data/constructors.csv")
drivers = pd.read_csv("../data/drivers.csv")

In [30]:
print("Races")
display(races.head())

Races

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N

In [31]:
print("Results")
display(results.head())

Results

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1

In [32]:
print("Constructors")
display(constructors.head(10))

Constructors

,constructorId,constructorRef,name,nationality,url
0,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
1,2,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,3,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso
5,6,ferrari,Ferrari,Italian,http://en.wikipedia.org/wiki/Scuderia_Ferrari
6,7,toyota,Toyota,Japanese,http://en.wikipedia.org/wiki/Toyota_Racing
7,8,super_aguri,Super Aguri,Japanese,http://en.wikipedia.org/wiki/Super_Aguri_F1
8,9,red_bull,Red Bull,Austrian,http://en.wikipedia.org/wiki/Red_Bull_Racing
9,10,force_india,Force India,Indian,http://en.wikipedia.org/wiki/Racing_Point_Forc...

In [33]:
print("Drivers")
display(drivers.head())

Drivers

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen

In [34]:
constructors[constructors["name"].str.contains("Red Bull", case = False)]

,constructorId,constructorRef,name,nationality,url
8,9,red_bull,Red Bull,Austrian,http://en.wikipedia.org/wiki/Red_Bull_Racing

In [60]:
redbull_results = results[results["constructorId"]==9]
redbull_results = pd.merge(redbull_results,races, on = "raceId",suffixes=('', '_race'))

In [61]:
print(redbull_results.shape)

(788, 69)

In [62]:
redbull_results.head()

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time_x,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId,year_x,round_x,circuitId_x,name_x,date_x,time_y,url_x,fp1_date_x,fp1_time_x,fp2_date_x,fp2_time_x,fp3_date_x,fp3_time_x,quali_date_x,quali_time_x,sprint_date_x,sprint_time_x,year_y,round_y,circuitId_y,name_y,date_y,time,url_y,fp1_date_y,fp1_time_y,fp2_date_y,fp2_time_y,fp3_date_y,fp3_time_y,quali_date_y,quali_time_y,sprint_date_y,sprint_time_y,year,round,circuitId,name,date,time_race,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,14,18,14,9,9,8,\N,R,14,0.0,25,\N,\N,21,11,1:29.502,213.300,4,2008,1,1,Australian Grand Prix,2008-03-16,04:30:00,http://en.wikipedia.org/wiki/2008_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,2008,1,1,Australian Grand Prix,2008-03-16,04:30:00,http://en.wikipedia.org/wiki/2008_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,2008,1,1,Australian Grand Prix,2008-03-16,04:30:00,http://en.wikipedia.org/wiki/2008_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,17,18,17,9,10,14,\N,R,17,0.0,0,\N,\N,\N,\N,\N,\N,4,2008,1,1,Australian Grand Prix,2008-03-16,04:30:00,http://en.wikipedia.org/wiki/2008_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,2008,1,1,Australian Grand Prix,2008-03-16,04:30:00,http://en.wikipedia.org/wiki/2008_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,2008,1,1,Australian Grand Prix,2008-03-16,04:30:00,http://en.wikipedia.org/wiki/2008_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,29,19,17,9,10,6,7,7,7,2.0,56,+1:08.130,5546685,53,12,1:36.696,206.366,1,2008,2,2,Malaysian Grand Prix,2008-03-23,07:00:00,http://en.wikipedia.org/wiki/2008_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,2008,2,2,Malaysian Grand Prix,2008-03-23,07:00:00,http://en.wikipedia.org/wiki/2008_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,2008,2,2,Malaysian Grand Prix,2008-03-23,07:00:00,http://en.wikipedia.org/wiki/2008_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,31,19,14,9,9,12,9,9,9,0.0,56,+1:16.220,5554775,55,9,1:36.206,207.417,1,2008,2,2,Malaysian Grand Prix,2008-03-23,07:00:00,http://en.wikipedia.org/wiki/2008_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,2008,2,2,Malaysian Grand Prix,2008-03-23,07:00:00,http://en.wikipedia.org/wiki/2008_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,2008,2,2,Malaysian Grand Prix,2008-03-23,07:00:00,http://en.wikipedia.org/wiki/2008_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,51,20,17,9,10,11,7,7,7,2.0,57,+45.473,5512443,51,8,1:34.305,206.597,1,2008,3,3,Bahrain Grand Prix,2008-04-06,11:30:00,http://en.wikipedia.org/wiki/2008_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,2008,3,3,Bahrain Grand Prix,2008-04-06,11:30:00,http://en.wikipedia.org/wiki/2008_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,2008,3,3,Bahrain Grand Prix,2008-04-06,11:30:00,http://en.wikipedia.org/wiki/2008_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N

In [63]:
print(redbull_results.columns)

Index(['resultId', 'raceId', 'driverId', 'constructorId', 'number', 'grid',
       'position', 'positionText', 'positionOrder', 'points', 'laps', 'time_x',
       'milliseconds', 'fastestLap', 'rank', 'fastestLapTime',
       'fastestLapSpeed', 'statusId', 'year_x', 'round_x', 'circuitId_x',
       'name_x', 'date_x', 'time_y', 'url_x', 'fp1_date_x', 'fp1_time_x',
       'fp2_date_x', 'fp2_time_x', 'fp3_date_x', 'fp3_time_x', 'quali_date_x',
       'quali_time_x', 'sprint_date_x', 'sprint_time_x', 'year_y', 'round_y',
       'circuitId_y', 'name_y', 'date_y', 'time', 'url_y', 'fp1_date_y',
       'fp1_time_y', 'fp2_date_y', 'fp2_time_y', 'fp3_date_y', 'fp3_time_y',
       'quali_date_y', 'quali_time_y', 'sprint_date_y', 'sprint_time_y',
       'year', 'round', 'circuitId', 'name', 'date', 'time_race', 'url',
       'fp1_date', 'fp1_time', 'fp2_date', 'fp2_time', 'fp3_date', 'fp3_time',
       'quali_date', 'quali_time', 'sprint_date', 'sprint_time'],
      dtype='object')

In [64]:
print(redbull_results["year"].unique())

[2008 2007 2006 2005 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018
 2019 2020 2021 2022 2023 2024]

In [75]:
grouped = redbull_results.groupby("year")["points"].sum().reset_index()
grouped= grouped.rename(columns = {"points": "Total Points"})

In [ ]:
wins = redbull_results[redbull_results["positionOrder"]==1]
annual_win_count= wins.groupby("year").size().reset_index(name="wins")

annual_win_count.head()

   year  wins
0  2009     6
1  2010     9
2  2011    12
3  2012     7
4  2013    13

In [83]:
podiums = redbull_results[redbull_results["positionOrder"]<=3]
annual_podium_count= podiums.groupby("year").size().reset_index(name ="podiums")

annual_podium_count.head()

   year  podiums
0  2006        1
1  2007        1
2  2008        1
3  2009       16
4  2010       20